# Generated by Django 3.2.9 on 2021-12-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0003_alter_rasm_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasm',
            name='photo',
            field=models.FileField(upload_to='static/'),
        ),
    ]
